// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpcTjy-P-PLRf-_9wlAAQxrynde6-yPJQ',
    appId: '1:133593667373:web:533d433ae16ffb429ca5a4',
    messagingSenderId: '133593667373',
    projectId: 'shift-project-usjr-saspitsia',
    authDomain: 'shift-project-usjr-saspitsia.firebaseapp.com',
    storageBucket: 'shift-project-usjr-saspitsia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh2FcrcITXYdC4ne4Gt67xR_lXVFInZdI',
    appId: '1:133593667373:android:f72a2edcc2e3bc689ca5a4',
    messagingSenderId: '133593667373',
    projectId: 'shift-project-usjr-saspitsia',
    storageBucket: 'shift-project-usjr-saspitsia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkQjdlGsWvVx4Kk8S-_CkzMLwv1Y4cMw',
    appId: '1:133593667373:ios:1ad6f24def410b309ca5a4',
    messagingSenderId: '133593667373',
    projectId: 'shift-project-usjr-saspitsia',
    storageBucket: 'shift-project-usjr-saspitsia.appspot.com',
    androidClientId: '133593667373-vph5hef324mmjv1gm9rt2vf9uq9qfomf.apps.googleusercontent.com',
    iosClientId: '133593667373-doh9mahni8b7mmg3j57p9dk2dlm6gip8.apps.googleusercontent.com',
    iosBundleId: 'com.example.shiftProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkQjdlGsWvVx4Kk8S-_CkzMLwv1Y4cMw',
    appId: '1:133593667373:ios:65a40fd81c404faa9ca5a4',
    messagingSenderId: '133593667373',
    projectId: 'shift-project-usjr-saspitsia',
    storageBucket: 'shift-project-usjr-saspitsia.appspot.com',
    androidClientId: '133593667373-vph5hef324mmjv1gm9rt2vf9uq9qfomf.apps.googleusercontent.com',
    iosClientId: '133593667373-2lnb1ask9fkgvllos478fihkambcifej.apps.googleusercontent.com',
    iosBundleId: 'com.example.shiftProject.RunnerTests',
  );
}
